### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by montyly** [crytic/fuzz-utils#19]
- [ ] Fix versioning (0.0.1 is on pypi, but should be 0.1.0 :) )
- [ ] https://github.com/crytic/fuzz-utils/issues/8 
- [ ] https://github.com/crytic/fuzz-utils/issues/18
- [ ] https://github.com/crytic/fuzz-utils/issues/7
